import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sổ Xố Miền Trung",
  description: "Generated by create next app",
  icons: "/logo.svg",
  keywords: ["soxovn", "soxokienthiet"]
};
export default function SXMBLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <section>{children}</section>
}